package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
@RequestMapping("AcctInq")
public class SpringrestserverApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringrestserverApplication.class, args);
	}

	@PostMapping("accountInquiry")
	public ResponseEntity<String> accountEnquiry() {
		
		String resp="{\"accountInquiryRes\":{\"resHdr\":{\"consumerContext\":{\"applicationId\":\"EVL\",\"terminalId\":\"12345\"},\"serviceContext\":{\"uniqueMsgId\":\"83552691f84a-ea29-4102-91a1-4a6418543f24\",\"reqMsgDateTime\":\"2017-03-21T13:25:18.9151598+05:30\",\"timeZone\":\"2017-03-21T13:25:18.9151598+05:30\",\"serviceName\":\"accountInquiry\",\"serviceVersion\":\"1\",\"conversationId\":\"21212112\",\"parentMsgId\":\"31321212\"},\"providerContext\":{\"providerId\":\"CBS\",\"responseMsgDateTime\":\"2024-01-10T11:38:52.216\"},\"responseStatus\":{\"status\":\"0\",\"esbResDateTime\":\"2024-01-10 17:08:52.225985\"}},\"body\":{\"custId\":\"1102211005\",\"accountNumber\":\"1102110190029658\",\"title\":\"M\\/S\",\"name\":\"GHJKJHGHJKJH\",\"branchId\":\"1102\",\"branchDesc\":\"KORAMANGALA\",\"schemeCode\":\"11019\",\"schemeType\":\"SBA\",\"accountOpenDt\":\"2021-08-13T00:00:00.000\",\"accountStatus\":\"A\",\"accountBal\":[{\"balanceType\":\"LEDGER\",\"balanceAmount\":\"0.00\"},{\"balanceType\":\"AVAIL\",\"balanceAmount\":\"0.00\"},{\"balanceType\":\"EFFAVL\",\"balanceAmount\":\"0.00\"},{\"balanceType\":\"FLOAT\",\"balanceAmount\":\"0.00\"},{\"balanceType\":\"LIEN\",\"balanceAmount\":\"0.00\"},{\"balanceType\":\"DRWPWR\",\"balanceAmount\":\"0.00\"},{\"balanceType\":\"ACCBAL\",\"balanceAmount\":\"0.00\"},{\"balanceType\":\"SHADOW\",\"balanceAmount\":\"0.00\"},{\"balanceType\":\"FUTBAL\",\"balanceAmount\":\"0.00\"}]}}}";
		
		 return new  ResponseEntity(resp, HttpStatus.OK);
		//return resp;
	}
	@PostMapping("getRetailCustomerInfo")
	public String customerEnqResponse() {
		
		String custresp="{\n"
				+ "   \"getRetailCustomerInfoRes\":{\n"
				+ "      \"resHdr\":{\n"
				+ "         \"consumerContext\":{\n"
				+ "            \"applicationId\":\"EVL\"\n"
				+ "         },\n"
				+ "         \"serviceContext\":{\n"
				+ "            \"uniqueMsgId\":\"83552023110312032671329\",\n"
				+ "            \"reqMsgDateTime\":\"2023-10-26T09:18:54.992Z\",\n"
				+ "            \"serviceName\":\"getRetailCustomerInfo\",\n"
				+ "            \"serviceVersion\":\"1\"\n"
				+ "         },\n"
				+ "         \"providerContext\":{\n"
				+ "            \"providerId\":\"CRM\"\n"
				+ "         },\n"
				+ "         \"responseStatus\":{\n"
				+ "            \"status\":\"0\",\n"
				+ "            \"esbResDateTime\":\"2023-11-06 16:23:59.147762\"\n"
				+ "         }\n"
				+ "      },\n"
				+ "      \"body\":{\n"
				+ "         \"customerDetails\":{\n"
				+ "            \"title\":\"MRS\",\n"
				+ "            \"firstName\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"lastName\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"middleName\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"accountName\":\"Shankara Narayanan Adaikalaraju\",\n"
				+ "            \"mothersMaidenName\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"fathersName\":\"DEYUL PRADHAN\",\n"
				+ "            \"mothersName\":\"MOTHER\",\n"
				+ "            \"maritialStatus\":\"MARRIED\",\n"
				+ "            \"husbandName\":\"Sanjoy Malik\",\n"
				+ "            \"addCategory\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"mobileNumber\":\"7908997277\",\n"
				+ "            \"customerType\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"branchName\":\"KORAMANGALA\",\n"
				+ "            \"branchId\":\"1102\",\n"
				+ "            \"ujjivanEmpId\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"custId\":\"1102208869\",\n"
				+ "            \"customerPhoto\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"customerSignature\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"centerNo\":\"0413\",\n"
				+ "            \"groupNo\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"mail\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"pan\":\"DQDPM7146H\",\n"
				+ "            \"aadhar\":\"195924097618\",\n"
				+ "            \"aadharDocumentCode\":\"Aadhar Card\",\n"
				+ "            \"KYCDocumentsNo\":\"195924097618\",\n"
				+ "            \"KYCDocumentsIssueDt\":\"2018-01-09\",\n"
				+ "            \"placeOfIssue\":\"INDIA\",\n"
				+ "            \"idIssueOrganisation\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"documentCode\":\"Aadhar Card\",\n"
				+ "            \"KYCDocumentsNo2\":\"195924097618\",\n"
				+ "            \"passPortIssueDt\":\"2018-01-09\",\n"
				+ "            \"additionalDocument\":\"No\",\n"
				+ "            \"KYCAdditionalDocument\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"KYCDocumentsNo3\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"address1\":\"BAMUNBANDHA\",\n"
				+ "            \"address2\":\"HJ\",\n"
				+ "            \"address3\":\"Karjjana\",\n"
				+ "            \"currentCity\":\"Bardhaman\",\n"
				+ "            \"currentState\":\"WEST BENGAL\",\n"
				+ "            \"currentPincode\":\"713102\",\n"
				+ "            \"currentDistrict\":\"Bardhaman\",\n"
				+ "            \"currentCountry\":\"INDIA\",\n"
				+ "            \"landmark\":\"Purba Para\",\n"
				+ "            \"permanentMobileNumber\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"permanentAddressSameAsAbove\":\"false\",\n"
				+ "            \"permanentAddress1\":\"BAMUNBANDHA\",\n"
				+ "            \"permanentAddress2\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"permanentAddress3\":\"Karjjana\",\n"
				+ "            \"permanentCity\":\"Bardhaman\",\n"
				+ "            \"permanentDistrict\":\"Bardhaman\",\n"
				+ "            \"permanentState\":\"WEST BENGAL\",\n"
				+ "            \"permanentCountry\":\"INDIA\",\n"
				+ "            \"permanentPincode\":\"713102\",\n"
				+ "            \"nearestLandmark\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"dateOfBirth\":\"1960-03-31\",\n"
				+ "            \"isMinor\":\"No\",\n"
				+ "            \"seniorCitizen\":\"true\",\n"
				+ "            \"nationality\":\"I\",\n"
				+ "            \"residenceStatus\":\"Resident Individual\",\n"
				+ "            \"form60/61\":\"Yes\",\n"
				+ "            \"gender\":\"Female\",\n"
				+ "            \"custLanguage\":\"English\",\n"
				+ "            \"occupationCode\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"occupationOthers\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"religion\":\"Hindu\",\n"
				+ "            \"religionOthers\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"category\":\"General\",\n"
				+ "            \"categoryOthers\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"CIFCreatedDate\":\"2020-10-09\",\n"
				+ "            \"grossAnnualIncome\":\"72000\",\n"
				+ "            \"qualification\":\"Others\",\n"
				+ "            \"qualificationOthers\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"politicalyExposed\":\"No\",\n"
				+ "            \"instaKitNumber\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"constitutionCode\":\"INDIVIDUAL\",\n"
				+ "            \"accountOwner\":\"MR Admin Admin\",\n"
				+ "            \"FATCADeclaration\":\"true\",\n"
				+ "            \"age\":\"33402719\",\n"
				+ "            \"staffFlag\":\"N\",\n"
				+ "            \"riskLevel1\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"customerClassification\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"FCUCheck\":\"false\",\n"
				+ "            \"voterId\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"chequeBook\":\"false\",\n"
				+ "            \"internetBanking\":\"false\",\n"
				+ "            \"mobileBanking\":\"true\",\n"
				+ "            \"SMSAlerts\":\"true\",\n"
				+ "            \"instaKit\":\"false\",\n"
				+ "            \"personalized\":\"false\",\n"
				+ "            \"ekycMode\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"registrationNum\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"dateOfIncorporation\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"layoutId\":\"102118\",\n"
				+ "            \"gstNumber\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"smsAlert\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"internatinalMobileNum\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"isdCode\":{\n"
				+ "               \n"
				+ "            },\n"
				+ "            \"fullKYCStatus\":{\n"
				+ "               \n"
				+ "            }\n"
				+ "         }\n"
				+ "      }\n"
				+ "   }\n"
				+ "}";
		
		return   custresp;
	}
	
	@PostMapping("vaultLookupService")
	public String aadharVaultResponse() {
		
		String response="{\n"
				+ "   \"vaultLookupServiceRes\":{\n"
				+ "      \"resHdr\":{\n"
				+ "         \"consumerContext\":{\n"
				+ "            \"applicationId\":\"EVL\"\n"
				+ "         },\n"
				+ "         \"serviceContext\":{\n"
				+ "            \"uniqueMsgId\":\"83552023110615180729629\",\n"
				+ "            \"reqMsgDateTime\":\"2018-07-16T16:07:45.5964699+05:30\",\n"
				+ "            \"serviceName\":\"vaultLookupService\",\n"
				+ "            \"serviceVersion\":\"1\"\n"
				+ "         },\n"
				+ "         \"providerContext\":{\n"
				+ "            \"providerId\":\"FinV\"\n"
				+ "         },\n"
				+ "         \"responseStatus\":{\n"
				+ "            \"status\":\"0\",\n"
				+ "            \"esbResDateTime\":\"2023-11-06 16:24:41.670417\"\n"
				+ "         }\n"
				+ "      },\n"
				+ "      \"body\":{\n"
				+ "         \"status\":\"success\",\n"
				+ "         \"entryTime\":\"2023-02-10T14:55:08\",\n"
				+ "         \"aadharNumber\":\"278597450610\",\n"
				+ "         \"aadharNumberForDisplay\":\"XXXXXXXX0345\",\n"
				+ "         \"aadharRefNum\":\"195924097618\",\n"
				+ "         \"token\":\"01001167BfvXGo6e78Gmr0BTXdpc6a3IVoMSCoy/FPmGIDyp2VYLbbVoV4AARYeLfa5h6krh\",\n"
				+ "         \"errorCode\":\"\"\n"
				+ "      }\n"
				+ "   }\n"
				+ "}";
		
		
		return response;
		
	}
	
	@PostMapping("genericSMSAPI")
	public String genericSMS() {
		
		String resp="{\n"
				+ "   \"genericSMSAPIRes\":{\n"
				+ "      \"resHdr\":{\n"
				+ "         \"consumerContext\":{\n"
				+ "            \"applicationId\":\"EVL\"\n"
				+ "         },\n"
				+ "         \"serviceContext\":{\n"
				+ "            \"serviceVersion\":\"1\",\n"
				+ "            \"uniqueMsgId\":\"8355EVL5cb822a85fb9461cb5ec99e590c48e4c\",\n"
				+ "            \"reqMsgDateTime\":\"2023-Oct-25:18:54:14\",\n"
				+ "            \"serviceName\":\"genericSMSAPI\"\n"
				+ "         },\n"
				+ "         \"providerContext\":{\n"
				+ "            \"providerId\":\"VER\"\n"
				+ "         },\n"
				+ "         \"responseStatus\":{\n"
				+ "            \"status\":\"0\",\n"
				+ "            \"esbResDateTime\":\"2023-10-25 18:54:38.431420\"\n"
				+ "         }\n"
				+ "      },\n"
				+ "      \"body\":{\n"
				+ "         \"code\":\"000\",\n"
				+ "         \"message\":\"Success, Message submitted successfully \",\n"
				+ "         \"jobId\":758455012\n"
				+ "      }\n"
				+ "   }\n"
				+ "}";
		
		return resp;
	}
	
}
